enum
{	
	CUST_ERROR_CALLBACK_TECENT_FAILED						= 90000,
	CUST_ERROR_OPENFILEFAIL									= 90001,
	CUST_ERROR_INVALID_WAVEFILE								= 90002, //非法的wave文件
	CUST_ERROR_NOT_HANDLE_COMPRESSED_WAVEFILE				= 90003, //无法处理压缩的wave文件
	CUST_ERROR_NOT_UNSUPORT_SAMPLE_RATE						= 90004,

	CUST_ERROR_AUDIO_SYNTHESIS_TEXTFILENAME_MISSING			= 90005,
	CUST_ERROR_AUDIO_SYNTHESIS_RESULTFILENAME_MISSING		= 90006,
	CUST_ERROR_AUDIO_TRANSCODING_SOURCEFILENAME_MISSING		= 90007,
	CUST_ERROR_AUDIO_TRANSCODING_DESTFILENAME_MISSING		= 90008,

	CUST_ERROR_AUDIO_SYNTHESIS_FAILED						= 99997,
	CUST_ERROR_AUDIO_TRANSCODING_FAILED						= 99998,
	CUST_ERROR_UNKNOWN										= 99999
};